language: node_js
node_js:
  - "0.11"
  - "0.10"

before_install:
  - npm install -g grunt-cli
after_script:
  - grunt publish
branches:
  only:
    - master

env:
  global:
    secure: "eDwWEbH6AzzU8kk0giqisGnl2AE61Ny2O68NNSM5JIc3mwJkW+k1lhbw/XtmB4e4SCtwxLEqAhlGBSL1R/pQ/RujjR6ck/4Gnwnyg/naE3gqvZrnbkff8/NsCz2lQSZcCBiEkvnVTrrBQ/uwB0JdD1OWvfkkF9kY4q9wHoBwFW8="